// Log in user
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// Register user
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// Get user details
export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS"
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL"

// Update the user profile 
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS"
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL"
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"

//Admin user list request
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST' 
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL" 
export const USER_LIST_RESET = "USER_LIST_RESET"

// Admin delete user
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL ="USER_DELETE_FAIL"
export const USER_DELETE_RESET ="USER_DELETE_RESET"


// Admin request user by id 
export const ADMIN_GET_USER_REQUEST = "ADMIN_GET_USER_REQUEST"
export const ADMIN_GET_USER_SUCCESS = "ADMIN_GET_USER_SUCCESS"
export const ADMIN_GET_USER_FAIL ="ADMIN_GET_USER_FAIL"

// Admin update user
export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST"
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS"
export const ADMIN_UPDATE_USER_FAIL ="ADMIN_UPDATE_USER_FAIL"
export const ADMIN_UPDATE_USER_RESET ="ADMIN_UPDATE_USER_RESET"

